# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\x05\x61gent\"3\n\x0bToolRequest\x12\x11\n\ttool_name\x18\x01 \x01(\t\x12\x11\n\targuments\x18\x02 \x01(\t\"\x1e\n\x0cToolResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2C\n\x0c\x41gentService\x12\x33\n\x08\x43\x61llTool\x12\x12.agent.ToolRequest\x1a\x13.agent.ToolResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOOLREQUEST']._serialized_start=22
  _globals['_TOOLREQUEST']._serialized_end=73
  _globals['_TOOLRESPONSE']._serialized_start=75
  _globals['_TOOLRESPONSE']._serialized_end=105
  _globals['_AGENTSERVICE']._serialized_start=107
  _globals['_AGENTSERVICE']._serialized_end=174
# @@protoc_insertion_point(module_scope)
